### PR TITLE
Add possibility to run test from cmake and ctest

### PR DESCRIPTION
**Pull request by Gjacquenot**

### CODE REVIEW

**Comment by Gjacquenot** [comment]
:wave: @jacobwilliams , I did not put much context on this pull request: As I am not familiar with fpm, I find it useful to run tests without another building tool. It gives external users a quick way to see how to use your library!

**Comment by jacobwilliams** [comment]
Cool! Is this ready to go? If so I'll go ahead and merge it!

**Comment by Gjacquenot** [comment]
> Cool! Is this ready to go? If so I'll go ahead and merge it!

Yes, you can merge it! Thanks for your enthusiasm

**Comment by Gjacquenot** [comment]
:wave: @jacobwilliams , can you have a look at this pull request, and merge it?

**Comment by jacobwilliams** [comment]
Done! Thanks for the contribution!

**Pull request merged**
